services:

  api:
    build:
      context: .
      dockerfile: src/TaskApi/Dockerfile

    container_name: taskapi-api

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=TasksDb;
        User Id=sa;
        Password=${MSSQL_SA_PASSWORD};
        TrustServerCertificate=True

    depends_on:
      - sqlserver


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: taskapi-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql


volumes:
  sqlserver_data: