apiVersion: apps/v1
kind: Deployment

metadata:
  name: taskapi

spec:
  replicas: 2

  selector:
    matchLabels:
      app: taskapi

  template:
    metadata:
      labels:
        app: taskapi

    spec:
      containers:
        - name: taskapi

          image: ghcr.io/kajetanbilinski/k8s-demo:sha-2865afff6e7412c671ce8c4d0369a6f83bcd4751
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: taskapi-secrets
                  key: ConnectionStrings__DefaultConnection

          readinessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 10